// <auto-generated />
using ExcelVideoLabeler.Infrastructure.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExcelVideoLabeler.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");

            modelBuilder.Entity("ExcelVideoLabeler.Domain.Entities.Config", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExceFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SheetCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Config");
                });

            modelBuilder.Entity("ExcelVideoLabeler.Domain.Entities.Sheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SheetCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SheetStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sheet");
                });

            modelBuilder.Entity("ExcelVideoLabeler.Domain.Entities.VideoAws.VideoAwsConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalVideoAws")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalVideoAwsDownloaded")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("VideoAwsConfig");
                });

            modelBuilder.Entity("ExcelVideoLabeler.Domain.Entities.VideoAws.VideoAwsInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AWSlink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackupTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Case")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateDownloadFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateOfIncident")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tester")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VideoStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("VideoAwsInfo");
                });

            modelBuilder.Entity("ExcelVideoLabeler.Domain.Entities.VideoInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Assign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BucketSmall")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DVRStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndShift")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionAmount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HasRedeemLater")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HighRisk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LoyaltyCard")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreTotalAmount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreTransDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreTransID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteEmployee")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartShift")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TOperatorID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TPACID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TotalAmount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransDateFormatted")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransDateWeekdayMask")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransNB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VideoStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YPredProba")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VideoInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
